Add Aztec
tinted-theming/schemes pull request #9
Opened 2024-02-22 15:48 UTC by TheNeverMan

Add Aztec theme to repository. (https://github.com/TheNeverMan/aztec-base16/)

2024-03-27 21:25 UTC, JamyGolden requested changes
Hello :smile: Can you remove the one comment? It doesn't add anything since the information is already contained within the yaml content itself. Once you remove it I'll merge the PR.

2024-03-27 21:25 UTC, JamyGolden commented on base16/aztec.yaml
> +# Aztec scheme for the Base16 Builder (https://github.com/chriskempson/base16-builder)
Can you remove this line?

2024-03-30 13:49 UTC, FredHappyface commented on base16/aztec.yaml
> +  base08: "EE2E00" # Red
Tbh love the comments here. Cheers :)

2024-03-31 18:23 UTC, TheNeverMan commented on base16/aztec.yaml
> +# Aztec scheme for the Base16 Builder (https://github.com/chriskempson/base16-builder)
Okay, I just copied yaml template from another theme within the repo, thought it is descriptive and appropriate.

2024-03-31 18:27 UTC, TheNeverMan commented on base16/aztec.yaml
> +  base08: "EE2E00" # Red
I copied the template from yaml file of 3024 theme. Thank contributor of that theme instead of me.

2024-03-31 18:36 UTC, TheNeverMan commented
File is updated. I removed the comment.

2024-03-31 18:37 UTC, FredHappyface approved these changes
lgtm

2024-04-01 10:42 UTC, JamyGolden approved these changes
Nice

2024-04-01 10:42 UTC, merged

2024-04-01 15:32 UTC, TheNeverMan commented
It is going to be automatically added to base16 gallery, right?

2024-04-01 17:36 UTC, JamyGolden commented
Yeah the builds happen every sunday, but I'll manually run it in the gallery now (the rest of the templates will be updated this sunday)